-- ============================================================================
-- SPRINT E1 · SEED CURRICULUM FlipMentoría
-- 6 etapas, ~22 bloques, 77 tareas (con detalles desde docs E0-E3)
-- Idempotente: ON CONFLICT (code) DO UPDATE
-- ============================================================================
SET LOCAL search_path = public;

-- ETAPAS

INSERT INTO edu_curriculum_stages (code, order_idx, title, emoji, description, expected_weeks, color) VALUES ('E0', 0, 'Fundación', '🏛️', 'Setup legal, financiero y de mentalidad antes de buscar deals.', 2, 'slate') ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, emoji=EXCLUDED.emoji, description=EXCLUDED.description, color=EXCLUDED.color;
INSERT INTO edu_curriculum_stages (code, order_idx, title, emoji, description, expected_weeks, color) VALUES ('E1', 1, 'Evaluar', '🔍', 'Encontrar y analizar deals: Buy Box, ZIPs, ARV, MAO, ofertas.', 4, 'amber') ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, emoji=EXCLUDED.emoji, description=EXCLUDED.description, color=EXCLUDED.color;
INSERT INTO edu_curriculum_stages (code, order_idx, title, emoji, description, expected_weeks, color) VALUES ('E2', 2, 'Estructurar', '🏗️', 'Levantar capital, armar equipo y plan de obra antes de comprar.', 4, 'blue') ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, emoji=EXCLUDED.emoji, description=EXCLUDED.description, color=EXCLUDED.color;
INSERT INTO edu_curriculum_stages (code, order_idx, title, emoji, description, expected_weeks, color) VALUES ('E3', 3, 'Ejecutar', '🔨', 'Gerencia activa de obra: supervisión, control financiero y calidad.', 8, 'orange') ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, emoji=EXCLUDED.emoji, description=EXCLUDED.description, color=EXCLUDED.color;
INSERT INTO edu_curriculum_stages (code, order_idx, title, emoji, description, expected_weeks, color) VALUES ('E4', 4, 'Estrategia de Salida', '💰', 'Vender o rentar: staging, pricing, marketing, screening.', 4, 'green') ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, emoji=EXCLUDED.emoji, description=EXCLUDED.description, color=EXCLUDED.color;
INSERT INTO edu_curriculum_stages (code, order_idx, title, emoji, description, expected_weeks, color) VALUES ('E5', 5, 'Escalar', '📈', 'Sistematizar y crecer: SOPs, red, equipo, múltiples deals.', 8, 'purple') ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, emoji=EXCLUDED.emoji, description=EXCLUDED.description, color=EXCLUDED.color;

-- BLOQUES
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E0.1', 0, 'Estructura legal y bancaria', 'LLC, EIN, Operating Agreement, cuenta de negocio, contabilidad, contador y abogado.' FROM edu_curriculum_stages WHERE code = 'E0' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E0.2', 1, 'Mentalidad y disciplina', 'Big Why, bloque diario de tiempo, quick win en semana 1.' FROM edu_curriculum_stages WHERE code = 'E0' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E0.3', 2, 'Stack operativo', 'Portal de gestión (Taskade), herramientas básicas activas.' FROM edu_curriculum_stages WHERE code = 'E0' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E1.1', 0, 'Buy Box', 'Reglas claras de qué casa SÍ y qué casa NO comprar.' FROM edu_curriculum_stages WHERE code = 'E1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E1.2', 1, 'Investigación de mercado', 'Selección y calificación de ZIPs, drive-throughs.' FROM edu_curriculum_stages WHERE code = 'E1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E1.3', 2, 'Análisis financiero', 'Comparables, ARV, costos de remodelación, MAO (regla 75%).' FROM edu_curriculum_stages WHERE code = 'E1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E1.4', 3, 'Ofertas', 'Hacer ofertas formales, negociar, documentar.' FROM edu_curriculum_stages WHERE code = 'E1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E2.1', 0, 'Financiamiento', 'Hard Money, Private Money, HELOC, term sheets.' FROM edu_curriculum_stages WHERE code = 'E2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E2.2', 1, 'Networking', 'Eventos REIA, presencia física, follow-ups.' FROM edu_curriculum_stages WHERE code = 'E2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E2.3', 2, 'Wholesalers', 'Identificar, contactar y mantener relación con mayoristas.' FROM edu_curriculum_stages WHERE code = 'E2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E2.4', 3, 'Contratistas (GCs)', 'Identificar 10 GCs, reunirse, pedir bids, verificar.' FROM edu_curriculum_stages WHERE code = 'E2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E2.5', 4, 'Permisos y zonificación', 'Building Department, restricciones, inspecciones obligatorias.' FROM edu_curriculum_stages WHERE code = 'E2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E2.6', 5, 'Plan de obra (SOW)', 'Plantilla SOW, cronograma con hitos, contingencia 10-15%.' FROM edu_curriculum_stages WHERE code = 'E2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E3.1', 0, 'Supervisión de obra', 'Visitas, reuniones semanales con GC, documentación con fotos.' FROM edu_curriculum_stages WHERE code = 'E3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E3.2', 1, 'Control financiero', 'Draw schedule, budget tracker, contingencia para retrasos.' FROM edu_curriculum_stages WHERE code = 'E3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E3.3', 2, 'Calidad e inspecciones', 'Inspecciones en hitos, resolver problemas en 24h, bitácoras.' FROM edu_curriculum_stages WHERE code = 'E3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E4.1', 0, 'Preparar para vender', 'Staging profesional, fotografía y video.' FROM edu_curriculum_stages WHERE code = 'E4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E4.2', 1, 'Pricing', 'Validar precio con comparables actuales, breakeven y ganancia neta.' FROM edu_curriculum_stages WHERE code = 'E4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E4.3', 2, 'Marketing', 'Publicar en mínimo 4 plataformas, open house.' FROM edu_curriculum_stages WHERE code = 'E4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E4.4', 3, 'Agente', 'Seleccionar agente de ventas.' FROM edu_curriculum_stages WHERE code = 'E4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E5.1', 0, 'Postmortem y sistematización', 'Análisis del primer flip, SOPs por etapa.' FROM edu_curriculum_stages WHERE code = 'E5' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E5.2', 1, 'Red y leads', 'Financiadores privados, sistema de generación de leads.' FROM edu_curriculum_stages WHERE code = 'E5' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E5.3', 2, 'Equipo y metas', 'Contratar PM, metas para el próximo año.' FROM edu_curriculum_stages WHERE code = 'E5' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;
INSERT INTO edu_curriculum_blocks (stage_id, code, order_idx, title, description) SELECT id, 'E5.4', 3, 'Múltiples deals y expansión', 'Operar deals simultáneos con estructura, segundo mercado.' FROM edu_curriculum_stages WHERE code = 'E5' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description;

-- TAREAS (77)
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.1.1', 1, 'Formar LLC en el estado donde se invertirá', 'Formar LLC en el estado donde se invertirá', 'El estudiante deberá formar la LLC en el estado donde planea ejecutar la inversión, validar disponibilidad del nombre, obtener Registered Agent, solicitar el EIN ante el IRS y archivar correctamente todos los documentos legales.', 'Certificate of Formation
EIN del IRS
Operating Agreement firmado
Cuenta bancaria de negocio
Archivo digital organizado', 4.0, 6.0, true, true, 'Sube el Certificate of Formation aprobado' FROM edu_curriculum_blocks WHERE code = 'E0.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.1.2', 2, 'Operating Agreement firmado', 'Operating Agreement firmado', 'Crear, adaptar, revisar y firmar el Operating Agreement de la LLC. Esto aplica incluso si la LLC es de un solo miembro.', 'Operating Agreement firmado y archivado en Taskade.
Debe incluir:
Nombre legal exacto de la LLC
Miembros de la LLC
Porcentajes de ownership
Tipo de administración: member-managed o manager-managed', 2.0, 3.0, true, true, 'Sube el Operating Agreement firmado (PDF)' FROM edu_curriculum_blocks WHERE code = 'E0.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.1.3', 3, 'Cuenta bancaria de negocio + tarjeta de crédito', 'Cuenta bancaria de negocio + tarjeta de crédito', 'Abrir una cuenta bancaria a nombre de la LLC y solicitar una tarjeta de crédito de negocio.', 'Cuenta bancaria de negocio activa + tarjeta de crédito de negocio aprobada + datos organizados y guardados en Taskade.
📋 Documentos para abrir cuenta:
Certificate of Formation aprobado (de E0.1.1)
EIN letter del IRS (de E0.1.1)
Operating Agreement firmado (de E0.1.2)
ID personal (passport o driver''s license)
Initial deposit ($100-$1,000 según banco)
Comprobante de domicilio (utility bill)', 2.0, 3.0, true, true, 'Sube el screenshot de la cuenta abierta + EIN letter' FROM edu_curriculum_blocks WHERE code = 'E0.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.1.4', 4, 'Software de contabilidad activo', 'Software de contabilidad activo', 'Configurar un software de contabilidad que registre todos los gastos del negocio desde el día 1. El estudiante debe dejar activa una herramienta donde pueda ver ingresos, gastos, flujo de caja y rentabilidad por propiedad o por deal.', 'Software de contabilidad configurado con:
Cuenta bancaria de negocio conectada
Tarjeta de crédito de negocio conectada
Categorías de Fix & Flip o Fix and Hold creadas
Transacciones sincronizadas
Ritual semanal de revisión en calendario
Reportes automáticos configurados', 3.0, 4.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E0.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.1.5', 5, 'Contador y abogado de real estate identificados', 'Contador y abogado de real estate identificados', 'Identificar, entrevistar y seleccionar mínimo:', 'CPA y abogado seleccionados con:
Nombre completo
Especialidad
Información de contacto
Fees aproximados
Tipo de servicio
Disponibilidad
Notas de entrevista
Todo documentado en Taskade dentro de la sección “Equipo Profesional”.', 4.0, 6.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E0.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.2.1', 1, 'Definir Big Why personal por escrito', 'Definir Big Why personal por escrito', 'Escribir 1–2 páginas detallando por qué estás haciendo este programa.', 'Big Why completo y firmado en Taskade + foto del documento físico colocado en un lugar visible.
Debe quedar:
firmado
fechado
impreso
visible diariamente', 2.0, 3.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E0.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.2.2', 2, 'Bloque diario de tiempo no negociable', 'Bloque diario de tiempo no negociable', 'Bloque diario de tiempo no negociable', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E0.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.2.3', 3, 'Quick Win en semana 1', 'Quick Win en semana 1', 'Lograr una victoria pequeña, concreta y tangible en la primera semana del programa para construir momentum.', 'Quick Win documentado en Taskade con evidencia. La evidencia puede ser: screenshot, foto, email, confirmación, captura de mensaje, registro a evento. term sheet recibido', 4.0, 6.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E0.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.3.1', 1, 'Setup completo del portal Taskade', 'Setup completo del portal Taskade', 'Configurar completamente el portal de Taskade (Fliptrack) con toda la estructura del programa lista para cargar tareas, avances, entregables y documentación del negocio.', 'Portal Fliptrack organizado y funcional con:
carpetas creadas y estructura del programa visible
espacios de entregables listos
accesos funcionando y sistema preparado para seguimiento.', 3.0, 4.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E0.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E0.3.2', 2, 'Stack de herramientas básico activo', 'Stack de herramientas básico activo', 'Stack de herramientas básico activo', NULL, 2.0, 3.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E0.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.1.1', 1, 'Construir 5 Buy Box para estrategia de RENTA', 'Construir 5 Buy Box para estrategia de RENTA', 'Construir 5 Buy Box para estrategia de RENTA', NULL, NULL, NULL, false, true, 'Sube tu Buy Box (puede ser un JSON/Sheet)' FROM edu_curriculum_blocks WHERE code = 'E1.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.1.2', 2, 'Construir 5 Buy Box para estrategia de VENTA (Fix & Flip)', 'Construir 5 Buy Box para estrategia de VENTA (Fix & Flip)', 'Construir 5 Buy Box para Fix & Flip, cada uno en un ZIP Code distinto, con ARV objetivo, MAO calculado y comparables reales.', '5 Buy Box de venta completos, cada uno con:
ZIP Code definido
ARV objetivo
MAO calculado
margen mínimo esperado
DOM máximo permitido
perfil del comprador final
3 comparables reales vendidos
screenshots y links de evidencia', 6.0, 8.0, false, true, 'Sube tu Buy Box (puede ser un JSON/Sheet)' FROM edu_curriculum_blocks WHERE code = 'E1.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.1.3', 3, 'Lista de 20 características que SÍ quiere', 'Lista de 20 características que SÍ quiere', 'Construir una lista de 20 características positivas que una propiedad debe tener para entrar en el Buy Box.', 'Lista de 20 características numeradas con explicación breve de por qué cada una importa.
La lista debe cubrir: estructura, distribución, sistemas, ubicación', 1.0, 2.0, false, true, 'Sube tu Buy Box (puede ser un JSON/Sheet)' FROM edu_curriculum_blocks WHERE code = 'E1.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.1.4', 4, 'Lista de 20 características que NO quiere (red flags)', 'Lista de 20 características que NO quiere (red flags)', 'Construir una lista de 20 red flags que descalifican una propiedad automáticamente o que obligan a investigar mucho más antes de avanzar.', 'Lista de 20 red flags numeradas, cada una con:
razón del riesgo
herramienta para verificarlo
criterio claro de descarte', 1.0, 2.0, false, true, 'Sube tu Buy Box (puede ser un JSON/Sheet)' FROM edu_curriculum_blocks WHERE code = 'E1.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.1.5', 5, 'Versión resumida del Buy Box (elevator pitch)', 'Versión resumida del Buy Box (elevator pitch)', 'Reducir el Buy Box completo a una versión corta, clara y profesional que pueda explicarse en menos de 1 minuto y enviarse fácilmente a contactos del ecosistema.', '2 documentos PDF de máximo 1 página cada uno:
1 Buy Box para renta
1 Buy Box para venta
Listos para:
enviar por WhatsApp
enviar por email
compartir en networking
usar en llamadas y reuniones', 1.0, 1.0, false, true, 'Sube tu Buy Box (puede ser un JSON/Sheet)' FROM edu_curriculum_blocks WHERE code = 'E1.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.2.1', 1, 'Investigación de mercado profunda por ZIP', 'Investigación de mercado profunda por ZIP', 'Construir un informe completo para cada uno de los 5 ZIP Codes seleccionados, usando datos reales del comportamiento del mercado durante los últimos 12 meses.', '5 informes completos, uno por cada ZIP, incluyendo:
DOM promedio
precio promedio por sqft
tendencia de precios últimos 12 meses
absorción mensual
sale-to-list ratio
perfil de comprador
screenshots y fuentes verificables
Todo organizado dentro de Taskade.', 4.0, 5.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E1.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.2.2', 2, 'Calificación A/B/C del ZIP en 5 variables', 'Calificación A/B/C del ZIP en 5 variables', 'Calificar cada ZIP Code en 5 variables clave: crimen, escuelas, transporte, desarrollo futuro, empleo/comercio', 'Matriz con 5 ZIP Codes × 5 variables, incluyendo:
calificación A/B/C por variable
justificación breve de cada celda
screenshots de soporte
clasificación final del ZIP
perfil de comprador o inquilino esperado', 2.0, 2.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E1.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.2.3', 3, 'Visita física al ZIP Code (drive-through)', 'Visita física al ZIP Code (drive-through)', 'Manejar por mínimo 3 de los 5 ZIP Codes seleccionados en 2 horarios distintos y documentar la visita con fotos, notas y observaciones reales.', 'Notas de campo de 1 página por ZIP + galería de 5–10 fotos por ZIP.
Debe quedar documentado en Taskade como: “Field Notes — ZIP [#####]”', 2.0, 3.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E1.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.2.4', 4, 'Identificar zonas A, B y C de la ciudad', 'Identificar zonas A, B y C de la ciudad', 'Crear un mapa de la ciudad objetivo clasificando las zonas A, B y C, y asignar una estrategia coherente para cada tipo de zona.', 'Mapa con zonas A/B/C + documento con justificación y estrategia por zona. Debe subirse a Taskade como: “Mapa de Zonas — [Ciudad]”', 2.0, 2.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E1.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.3.1', 1, 'Analizar 10 casas comparables por ZIP Code', 'Analizar 10 casas comparables por ZIP Code', 'Analizar 10 casas comparables vendidas por cada ZIP Code seleccionado.', 'Tabla “Comparables por ZIP” con 50 registros, incluyendo: dirección, fecha de venta, precio vendido, sqft, habitaciones / baños, condición, $/sqft, link de Zillow o Redfin, características que aumentan valor', 30.0, 45.0, false, true, 'Sube el análisis de comparables, ARV y MAO calculado' FROM edu_curriculum_blocks WHERE code = 'E1.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.3.2', 2, 'Calcular ARV (conservador + optimista)', 'Calcular ARV (conservador + optimista)', 'Calcular el ARV de cada una de las 50 propiedades usando comparables reales. Cada propiedad debe tener:', '50 ARVs documentados con:
3 comparables usados
$/sqft promedio
ajustes aplicados
ARV base
ARV conservador
ARV optimista', 20.0, 30.0, false, true, 'Sube el análisis de comparables, ARV y MAO calculado' FROM edu_curriculum_blocks WHERE code = 'E1.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.3.3', 3, 'Estimar remodelación por nivel', 'Estimar remodelación por nivel', 'Estimar el costo de remodelación de cada una de las 50 propiedades clasificando el nivel de trabajo:', '50 estimaciones de remodelación con:
nivel asignado
rango bajo y alto
desglose por categoría
contingencia
justificación basada en fotos', 15.0, 20.0, false, true, 'Sube el análisis de comparables, ARV y MAO calculado' FROM edu_curriculum_blocks WHERE code = 'E1.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.3.4', 4, 'Aplicar la Regla del 75% (MAO)', 'Aplicar la Regla del 75% (MAO)', 'Calcular el MAO de cada propiedad usando la fórmula:', 'Tabla con 50 MAO, incluyendo:
ARV conservador
rehab usado
MAO calculado
precio de lista
gap entre MAO y precio
clasificación de negociable o no negociable', 5.0, 10.0, true, true, 'Sube el análisis de comparables, ARV y MAO calculado' FROM edu_curriculum_blocks WHERE code = 'E1.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.4.1', 1, 'Enviar mínimo 10 ofertas formales al mes', 'Enviar mínimo 10 ofertas formales al mes', 'Enviar mínimo 10 ofertas formales al mes usando el MAO calculado previamente.', 'Log “Ofertas Enviadas — [Mes]” con:
propiedad
MAO
fecha de envío
canal utilizado
screenshot del email
LOI adjunto
estado de la oferta
respuesta recibida', 30.0, 45.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E1.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.4.2', 2, 'Negociar activamente cada oferta', 'Negociar activamente cada oferta', 'Negociar activamente cada oferta enviada. Cada deal activo debe tener mínimo 2 rondas de contraoferta antes de decidir si se acepta, se descarta o se deja en seguimiento.', 'Log de negociación con mínimo 2 contraofertas documentadas por cada deal activo.
Debe incluir:
oferta inicial
contraoferta del vendedor
respuesta del estudiante
fecha de cada ronda
tono de la conversación
decisión final
próximo seguimiento', 1.0, 2.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E1.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.4.3', 3, 'Identificar el "pain point" del vendedor', 'Identificar el "pain point" del vendedor', 'Por cada deal activo, hacer discovery del vendedor para identificar el pain point real detrás de la venta.', 'Ficha de discovery por cada deal activo con:
preguntas realizadas
respuestas del vendedor o agente
pain point identificado
estrategia de oferta ajustada
próximo paso de negociación', 30.0, 45.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E1.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E1.4.4', 4, 'Documentar resultado de cada oferta', 'Documentar resultado de cada oferta', 'Mantener actualizado semanalmente el estado de cada oferta enviada y construir un reporte mensual con métricas reales. El objetivo es que el estudiante sepa qué está funcionando, qué no y qué debe ajustar.', 'Log actualizado semanalmente + reporte mensual con:
estado de cada oferta
métricas clave
patrones identificados
3 ajustes propuestos para el siguiente mes', 15.0, 15.0, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E1.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.1.1', 1, 'Llamar y entrevistar 10 Hard Money Lenders', 'Llamar y entrevistar 10 Hard Money Lenders', 'Llamar y entrevistar 10 Hard Money Lenders', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.1.2', 2, 'Solicitar term sheets oficiales', 'Solicitar term sheets oficiales', 'Solicitar term sheets oficiales', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.1.3', 3, 'Investigar opciones de Private Money', 'Investigar opciones de Private Money', 'Investigar opciones de Private Money', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.1.4', 4, 'Evaluar HELOC sobre vivienda principal', 'Evaluar HELOC sobre vivienda principal', 'Evaluar HELOC sobre vivienda principal', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.1.5', 5, 'Elegir HML primario + backup', 'Elegir HML primario + backup', 'Elegir HML primario + backup', NULL, NULL, NULL, true, true, 'Sube los 2 term sheets (primario + backup)' FROM edu_curriculum_blocks WHERE code = 'E2.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.2.1', 1, 'Identificar y registrarse a 5 eventos', 'Identificar y registrarse a 5 eventos', 'Identificar y registrarse a 5 eventos', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.2.2', 2, 'Asistir físicamente a los eventos', 'Asistir físicamente a los eventos', 'Asistir físicamente a los eventos', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.2.3', 3, 'Follow-up en 48 horas', 'Follow-up en 48 horas', 'Follow-up en 48 horas', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.3.1', 1, 'Identificar 20 wholesalers activos', 'Identificar 20 wholesalers activos', 'Identificar 20 wholesalers activos', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.3.2', 2, 'Contactar y presentar Buy Box', 'Contactar y presentar Buy Box', 'Contactar y presentar Buy Box', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.3.3', 3, 'Llamada 1-a-1 con wholesalers', 'Llamada 1-a-1 con wholesalers', 'Llamada 1-a-1 con wholesalers', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.3.4', 4, 'Suscribirse a buyer lists', 'Suscribirse a buyer lists', 'Suscribirse a buyer lists', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.3.5', 5, 'Análisis express de cada deal entrante', 'Análisis express de cada deal entrante', 'Análisis express de cada deal entrante', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.4.1', 1, 'Identificar y contactar 10 GCs', 'Identificar y contactar 10 GCs', 'Identificar y contactar 10 GCs', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.4.2', 2, 'Reunión con cada GC', 'Reunión con cada GC', 'Reunión con cada GC', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.4.3', 3, 'Solicitar bid sobre propiedad muestra', 'Solicitar bid sobre propiedad muestra', 'Solicitar bid sobre propiedad muestra', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.4.4', 4, 'Verificar licencia, seguros y referencias', 'Verificar licencia, seguros y referencias', 'Verificar licencia, seguros y referencias', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.4.5', 5, 'Cultivar relación a largo plazo', 'Cultivar relación a largo plazo', 'Cultivar relación a largo plazo', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.5.1', 1, 'Investigar proceso de permisos', 'Investigar proceso de permisos', 'Investigar proceso de permisos', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.5' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.5.2', 2, 'Visita o llamada al Building Department', 'Visita o llamada al Building Department', 'Visita o llamada al Building Department', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.5' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.5.3', 3, 'Restricciones de zonificación por ZIP', 'Restricciones de zonificación por ZIP', 'Restricciones de zonificación por ZIP', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.5' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.5.4', 4, 'Mapear inspecciones obligatorias', 'Mapear inspecciones obligatorias', 'Mapear inspecciones obligatorias', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.5' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.5.5', 5, 'Identificar programas especiales', 'Identificar programas especiales', 'Identificar programas especiales', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.5' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.6.1', 1, 'Crear plantilla maestra de SOW', 'Crear plantilla maestra de SOW', 'Crear plantilla maestra de SOW', NULL, NULL, NULL, true, true, 'Sube tu plantilla SOW maestra' FROM edu_curriculum_blocks WHERE code = 'E2.6' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.6.2', 2, 'Aplicar SOW a un caso real', 'Aplicar SOW a un caso real', 'Aplicar SOW a un caso real', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.6' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.6.3', 3, 'Cronograma con hitos clave', 'Cronograma con hitos clave', 'Cronograma con hitos clave', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.6' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E2.6.4', 4, 'Calcular contingencia 10-15%', 'Calcular contingencia 10-15%', 'Calcular contingencia 10-15%', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E2.6' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E3.1.1', 1, 'Visitar la propiedad mínimo 3 veces por semana', 'Visitar la propiedad mínimo 3 veces por semana', 'Visitar la propiedad mínimo 3 veces por semana', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E3.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E3.1.2', 2, 'Reunión semanal de avance con el GC', 'Reunión semanal de avance con el GC', 'Reunión semanal de avance con el GC', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E3.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E3.1.3', 3, 'Documentar con fotos antes/durante/después', 'Documentar con fotos antes/durante/después', 'Documentar con fotos antes/durante/después', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E3.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E3.2.1', 1, 'Controlar cada pago con draw schedule', 'Controlar cada pago con draw schedule', 'Controlar cada pago con draw schedule', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E3.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E3.2.2', 2, 'Budget tracker actualizado semanalmente', 'Budget tracker actualizado semanalmente', 'Budget tracker actualizado semanalmente', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E3.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E3.2.3', 3, 'Plan de contingencia para retrasos', 'Plan de contingencia para retrasos', 'Plan de contingencia para retrasos', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E3.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E3.3.1', 1, 'Inspecciones de obra en hitos clave', 'Inspecciones de obra en hitos clave', 'Inspecciones de obra en hitos clave', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E3.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E3.3.2', 2, 'Resolver problemas en 24 horas', 'Resolver problemas en 24 horas', 'Resolver problemas en 24 horas', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E3.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E3.3.3', 3, 'Generación de bitácoras semanales', 'Generación de bitácoras semanales', 'Generación de bitácoras semanales', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E3.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E4.1.1', 1, 'Staging profesional completado', 'Staging profesional completado', 'Staging profesional completado', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E4.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E4.1.2', 2, 'Fotografía y video profesional listos', 'Fotografía y video profesional listos', 'Fotografía y video profesional listos', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E4.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E4.2.1', 1, 'Precio de lista validado con comparables actuales', 'Precio de lista validado con comparables actuales', 'Precio de lista validado con comparables actuales', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E4.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E4.2.2', 2, 'Calcular breakeven y ganancia neta antes de listar', 'Calcular breakeven y ganancia neta antes de listar', 'Calcular breakeven y ganancia neta antes de listar', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E4.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E4.3.1', 1, 'Publicar en mínimo 4 plataformas', 'Publicar en mínimo 4 plataformas', 'Publicar en mínimo 4 plataformas', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E4.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E4.3.2', 2, 'Open house en la primera semana', 'Open house en la primera semana', 'Open house en la primera semana', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E4.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E4.4.1', 1, 'Agente de ventas seleccionado', 'Agente de ventas seleccionado', 'Agente de ventas seleccionado', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E4.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E5.1.1', 1, 'Análisis detallado del primer flip', 'Análisis detallado del primer flip', 'Análisis detallado del primer flip', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E5.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E5.1.2', 2, 'SOPs creados para cada etapa del proceso', 'SOPs creados para cada etapa del proceso', 'SOPs creados para cada etapa del proceso', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E5.1' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E5.2.1', 1, 'Red de financiadores privados en construcción', 'Red de financiadores privados en construcción', 'Red de financiadores privados en construcción', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E5.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E5.2.2', 2, 'Sistema de generación de leads activo', 'Sistema de generación de leads activo', 'Sistema de generación de leads activo', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E5.2' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E5.3.1', 1, 'Contratar Project Manager', 'Contratar Project Manager', 'Contratar Project Manager', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E5.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E5.3.2', 2, 'Metas para el próximo año definidas', 'Metas para el próximo año definidas', 'Metas para el próximo año definidas', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E5.3' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E5.4.1', 1, 'Múltiples deals simultáneos con estructura', 'Múltiples deals simultáneos con estructura', 'Múltiples deals simultáneos con estructura', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E5.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;
INSERT INTO edu_curriculum_tasks (block_id, code, order_idx, title, short_title, description, deliverable, estimated_hours_min, estimated_hours_max, is_critical, evidence_required, evidence_hint) SELECT id, 'E5.4.2', 2, 'Evaluar expansión a segundo mercado', 'Evaluar expansión a segundo mercado', 'Evaluar expansión a segundo mercado', NULL, NULL, NULL, false, true, NULL FROM edu_curriculum_blocks WHERE code = 'E5.4' ON CONFLICT (code) DO UPDATE SET title=EXCLUDED.title, description=EXCLUDED.description, deliverable=EXCLUDED.deliverable, estimated_hours_min=EXCLUDED.estimated_hours_min, estimated_hours_max=EXCLUDED.estimated_hours_max, evidence_hint=EXCLUDED.evidence_hint;

-- DEPENDENCIAS CLAVE
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E0.1.2'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E0.1.1') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E0.1.3'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E0.1.2') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E0.1.4'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E0.1.3') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.1.5'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.1.1') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.1.5'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.1.2') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.2.2'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.2.1') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.3.4'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.3.2') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.3.4'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.3.3') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.4.1'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.3.4') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.1.5'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.1.1') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.1.5'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.1.2') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.3.2'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.1.5') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.4.3'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.4.2') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.6.2'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.6.1') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E3.2.1'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E2.6.3') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E4.2.1'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E1.3.2') ON CONFLICT (task_id, depends_on_id) DO NOTHING;
INSERT INTO edu_curriculum_deps (task_id, depends_on_id) SELECT (SELECT id FROM edu_curriculum_tasks WHERE code = 'E5.1.2'), (SELECT id FROM edu_curriculum_tasks WHERE code = 'E5.1.1') ON CONFLICT (task_id, depends_on_id) DO NOTHING;

-- RECURSOS ESENCIALES (semilla curada — el resto se carga después)
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('tool','E0','E0.1','E0.1.1','Northwest Registered Agent','Mejor calidad/precio para Registered Agent en cualquier estado','https://www.northwestregisteredagent.com','national',NULL,NULL,'paid','$39 + state fee','Desde deal #0',ARRAY['llc','registered-agent']::text[],true) ON CONFLICT DO NOTHING;
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('tool','E0','E0.1','E0.1.1','LegalZoom','Servicio popular pero más caro','https://www.legalzoom.com','national',NULL,NULL,'paid','$149 + state fee','Desde deal #0',ARRAY['llc']::text[],false) ON CONFLICT DO NOTHING;
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('tool','E0','E0.1','E0.1.1','IRS · EIN Online','Saca tu EIN gratis (no pagues a nadie por esto)','https://www.irs.gov/businesses/small-businesses-self-employed/apply-for-an-employer-identification-number-ein-online','national',NULL,NULL,'free',NULL,'Después de aprobar LLC',ARRAY['ein','irs']::text[],true) ON CONFLICT DO NOTHING;
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('tool','E1','E1.1','E1.1.1','PropStream','Pull de propiedades + skip tracing nacional','https://www.propstream.com','national',NULL,NULL,'paid','~$99/mes','Desde deal #1',ARRAY['data','leads','skip-tracing']::text[],true) ON CONFLICT DO NOTHING;
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('tool','E1','E1.3','E1.3.2','Zillow','Comparables y mercado por ZIP','https://www.zillow.com','national',NULL,NULL,'free',NULL,'Siempre',ARRAY['comps','market']::text[],true) ON CONFLICT DO NOTHING;
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('tool','E1','E1.3','E1.3.4','BiggerPockets BRRRR Calculator','Underwriting express con regla 75%','https://www.biggerpockets.com/calc','national',NULL,NULL,'freemium',NULL,'Desde deal #1',ARRAY['mao','underwriting']::text[],true) ON CONFLICT DO NOTHING;
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('contact','E2','E2.1','E2.1.1','Kiavi (ex-LendingHome)','Hard Money Lender nacional para fix & flip','https://www.kiavi.com','national',NULL,NULL,'paid','Tasas 9-12%','Desde deal #1',ARRAY['hml','financing']::text[],true) ON CONFLICT DO NOTHING;
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('contact','E2','E2.1','E2.1.1','RCN Capital','HML nacional con experiencia en flippers nuevos','https://www.rcncapital.com','national',NULL,NULL,'paid','Tasas similares','Desde deal #1',ARRAY['hml','financing']::text[],true) ON CONFLICT DO NOTHING;
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('tool','E0','E0.2','E0.3.1','Taskade','Portal de gestión recomendado por la mentoría','https://www.taskade.com','national',NULL,NULL,'freemium',NULL,'Setup semana 1',ARRAY['pm','portal','stack']::text[],true) ON CONFLICT DO NOTHING;
INSERT INTO edu_resources (kind, stage_code, block_code, task_code, name, description, url, geo_scope, state, city, price_tier, price_note, essential_when, tags, is_recommended) VALUES ('tool','E3','E3.1','E3.1.3','CompanyCam','Documentación fotos de obra georeferenciadas','https://www.companycam.com','national',NULL,NULL,'paid','$24/usr/mes','Cuando empieza obra',ARRAY['photos','quality']::text[],true) ON CONFLICT DO NOTHING;

-- ============================================================================
-- FIN seed. Total: 6 etapas, 22 bloques, 77 tareas, 16 dependencias, 10 recursos.
-- ============================================================================