-- 🗺️ Seed del Mapa de Conexiones — linaje curado de las 4 empresas (14-jul).
-- Idempotente (on conflict do nothing). Los estados reflejan la realidad de HOY:
-- lo arreglado el 14-jul queda OK con nota "antes BUG"; lo vigente a revisar queda warn/bug.
-- Este seed es el punto de partida; el equipo lo edita desde /mapa (todo queda en el audit).

insert into data_lineage_map (empresa, sistema, grupo, dato, base, tabla, columna, formula, nota, estado, orden) values
-- ═══ FIX & FLIP · Ficha de Casa ═══
('Fix & Flip','Ficha de Casa','Compra y financiación','Etapa actual','Fix & Flip','Propiedades','Estado Actual',null,null,'ok',1),
('Fix & Flip','Ficha de Casa','Compra y financiación','Compra','Fix & Flip','Propiedades','Precio de compra (fldeJFg5lD5L69Hio)','v_property_360.compra → deal (cadena única osFichaNums)','antes BUG (leía campo inexistente → $0 en todas las fichas) — arreglado 14-jul','ok',2),
('Fix & Flip','Ficha de Casa','Compra y financiación','Remodelación (draws)','Fix & Flip','Desglose Draws','Total Draws (fld208iuposxA20W0)',null,'⚠ vacío en 7 casas con obra (faltan draws en Airtable — PENDIENTE_HUMANO)','warn',3),
('Fix & Flip','Ficha de Casa','Compra y financiación','All-in','Supabase (vista)','v_ff_portafolio','all_in','compra + Total Draws; fallback rehab REAL→ESTIMADA siempre rotulado','antes usaba rehab sin rotular — arreglado 14-jul','ok',4),
('Fix & Flip','Ficha de Casa','Compra y financiación','ARV','Fix & Flip','Propiedades','ARV (fldPmfjmdVv7PRxjK)',null,null,'ok',5),
('Fix & Flip','Ficha de Casa','Compra y financiación','Appraisal','Fix & Flip','Propiedades','Valuación por el Appraisal',null,null,'ok',6),
('Fix & Flip','Ficha de Casa','Compra y financiación','Equity incorporado','Supabase (vista)','v_ff_portafolio','arv − all_in','ARV − all-in (la MISMA cadena que la tarjeta)',null,'ok',7),
('Fix & Flip','Ficha de Casa','Compra y financiación','Déficit','Fix & Flip','Desglose Draws','Total Draws − Déficit Total (fldL4iMolqEibENFj)','[Total Draws − Déficit Total] − Down Payment (fldxuB3kYq8cNQHIK)','FALSO si Total Draws está vacío → guardrail: excluida del acumulado con badge "faltan draws"','warn',8),
('Fix & Flip','Ficha de Casa','Compra y financiación','HML (pago)','Fix & Flip','Datos por casa','Monto HML','pago mensual = préstamo × tasa/12',null,'ok',9),
('Fix & Flip','Ficha de Casa','Compra y financiación','Cash-out','Fix & Flip','Datos por casa','Valor Cash out',null,null,'ok',10),
('Fix & Flip','Ficha de Casa','Compra y financiación','MAO','Supabase (vista)','—','ARV×75% − remodelación − holding','calculado en el front (osCasa)',null,'ok',11),
('Fix & Flip','Ficha de Casa','Rentas (panel)','Renta mensual actual','Fix & Flip','Propiedades','Renta mensual actual (fldj3xoSM5amtrBOQ)',null,'⚠ 2 FUENTES: también existe Rentas·Inquilinos·Monto Renta — definir la canónica','warn',12),
('Fix & Flip','Ficha de Casa','Rentas (panel)','Gastos mensuales','Fix & Flip','Propiedades','Gastos mensuales actual (fldnid53AmifS7kK1)',null,'panel conectado por property_id el 14-jul (antes salía vacío)','ok',13),
('Fix & Flip','Ficha de Casa','Rentas (panel)','Flujo mensual','Supabase (vista)','v_ff_portafolio','flujo_mes','renta − gastos (UNA definición, la misma del Command Center)','antes BUG: panel vacío con casa rentada (Childress) — arreglado 14-jul','ok',14),
('Fix & Flip','Ficha de Casa','Rentas (panel)','Ocupación / unidades','Rentas','🚪 Unidades (espejo pm_units)','Estado = Ocupada','habitaciones juntas = 1 unidad (regla dueño)',null,'ok',15),
('Fix & Flip','Ficha de Casa','Rentas (panel)','Cobrado del mes','Rentas','💵 Pagos (espejo pm_payments)','Pago realizado','Σ pagos del mes por property_id',null,'ok',16),
('Fix & Flip','Ficha de Casa','Obra (panel)','Avance de obra','Remodelación','Propiedad en Reparación','Porcentaje avance obra %','avance real del Planner (v_remodel_progress) si existe',null,'ok',17),
('Fix & Flip','Ficha de Casa','Obra (panel)','Líder','Remodelación','Propiedad en Reparación','Lider asignado',null,null,'ok',18),
('Fix & Flip','Ficha de Casa','Obra (panel)','Presupuesto / gastado','Remodelación','Propiedad en Reparación','Presupuesto Remodelación interna / Gasto interno final',null,null,'ok',19),
('Fix & Flip','Ficha de Casa','Obra (panel)','Utilidad de obra','Remodelación','Propiedad en Reparación','Utilidad','preliminar si obra en curso','casa terminada sin registro de obra → "Obra finalizada" con resumen FF (14-jul)','ok',20),
-- ═══ FIX & FLIP · Command Center ═══
('Fix & Flip','Command Center','Patrimonio','Valor del portafolio','Supabase (vista)','v_ff_portafolio_kpi','Σ arv (modelo_negocio ≠ Operador y stage ≠ vendida)','$9,415,000 / 23 casas — cuadre exacto vs 11,450,000',null,'ok',1),
('Fix & Flip','Command Center','Patrimonio','Equity del portafolio','Supabase (vista)','v_ff_portafolio_kpi','Σ (arv − deuda)',null,null,'ok',2),
('Fix & Flip','Command Center','Patrimonio','Deuda del portafolio','Supabase (vista)','v_ff_portafolio','deuda (refi | HML por casa)','drill por casa + reconcile QBO Δ',null,'ok',3),
('Fix & Flip','Command Center','Patrimonio','Rendimiento anual (doble)','Supabase (vista)','v_ff_portafolio','flujo_mes / pago_deuda_mes','op = Σ flujo×12 · c/deuda = Σ (flujo − hml_payment − ref30_payment)×12','+$179,289 op / −$363,406 c/deuda','ok',4),
('Fix & Flip','Command Center','Patrimonio','Déficit del CEO','Fix & Flip','Desglose Draws','draws_menos_deficit (fldL4iMolqEibENFj)','[Total Draws − Déficit Total] − Down Payment','guardrail draws=0 con obra → excluida (−$289,188 / 7 casas)','warn',5),
('Fix & Flip','Command Center','Pipeline','All-in por casa','Supabase (vista)','v_ff_portafolio','all_in','compra + Total Draws (fallback *rehab rotulado)',null,'ok',6),
('Fix & Flip','Command Center','Pipeline','Margen por casa','Supabase (vista)','v_ff_portafolio','margen','arv − all_in',null,'ok',7),
('Fix & Flip','Command Center','Pipeline','Estrategia','Fix & Flip','Propiedades','Estrategia (palabra completa)',null,null,'ok',8),
-- ═══ FIX & FLIP · Analítica ═══
('Fix & Flip','Analítica','KPIs','Total operaciones','Supabase (vista)','v_property_360','count',null,null,'ok',1),
('Fix & Flip','Analítica','KPIs','Casas en renta','Supabase (vista)','v_property_360','count (etapa rentada/refinanciada)',null,null,'ok',2),
('Fix & Flip','Analítica','KPIs','Flujo del portafolio','Supabase (vista)','v_ff_portafolio','Σ flujo_mes',null,null,'ok',3),
('Fix & Flip','Analítica','KPIs','Concentración por inversionista','Supabase (vista)','v_inversionistas','capital_aportado / Σ','definición canónica de co-inversión ACTIVA (misma que módulo Inversionistas)','Jefferson 28.7% > umbral 25%','ok',4),
('Fix & Flip','Analítica','KPIs','Vendidas: ROI / utilidad','Fix & Flip','Datos por casa','Utilidad Neta / ROI / Precio de Venta','solo Arcadia con datos completos',null,'warn',5),
-- ═══ FIX & FLIP · Inversionistas (módulo) ═══
('Fix & Flip','Inversionistas','Ranking','Capital desplegado','Fix & Flip','Propiedades','Capital aportado (fldrePoqg3C3caiZ5)','columna PURA (capital_aportado) — no la coalesced','⚠ capital_inversionista difiere (Stonleigh 45k vs 35k) — usar SIEMPRE capital_aportado','warn',1),
('Fix & Flip','Inversionistas','Ranking','Co-inversionistas activos','Supabase (vista)','v_inversionistas','0 < ownership nuestro < 100%','100% = les compramos la parte (fuera) · 0% = operador · vendida = salida realizada',null,'ok',2),
('Fix & Flip','Inversionistas','Ranking','Rentabilidad por inversionista','Supabase (vista)','v_inversionistas','participación × (renta − gastos) × 12 ÷ capital','vendida = utilidad entregada ÷ capital · sin dato = "pendiente"',null,'ok',3),
-- ═══ FIX & FLIP · Underwriting ═══
('Fix & Flip','Underwriting','Cadena','Base HML','Fix & Flip','Propiedades + Desglose Draws','Precio de compra + Total Draws','préstamo bruto = %fin × (compra + draw total), punto fijo','UNA base — Calc 4 la lee de negocio.prestamo, nadie recalcula','ok',1),
('Fix & Flip','Underwriting','Cadena','Payoff del HML','Supabase (vista)','—','principal + hml_capitaliza','prioridad: override manual > pagado real Airtable > ⛓ calculado > saldo HML',null,'ok',2),
('Fix & Flip','Underwriting','Cadena','Pago mensual Harmony','Fix & Flip','Datos por casa','Tasa Interés HML','solo interés = préstamo ⛓ × tasa/12 (no depende de meses)',null,'ok',3),
('Fix & Flip','Underwriting','Cadena','Pago mensual refi (P&I)','Fix & Flip','Datos por casa','Monto préstamo Refi / tasa / plazo','amortizado sobre préstamo ⛓ Cash-Out (LTV × tasación / tope DSCR)',null,'ok',4),
('Fix & Flip','Underwriting','Cadena','ARV (tasador)','Supabase (vista)','v_arv_calibracion + motor ff-arv-engine','comps RentCast ajustados','mediana ponderada, MdAPE 4.9% sobre 12 casas',null,'ok',5),
-- ═══ FIX & FLIP · Portal Inversionista ═══
('Fix & Flip','Portal Inversionista','Métricas','Capital aportado','Supabase (vista)','inv_holdings','inversion_aportada',null,null,'ok',1),
('Fix & Flip','Portal Inversionista','Métricas','Cash-on-Cash','Supabase (vista)','inv_ledger (RPC)','renta − operativos − deuda (ventana 12m)','base REAL si hay rentas; si no, modelo (declarado con chip)',null,'ok',2),
('Fix & Flip','Portal Inversionista','Métricas','TIR / VPN 31 años','Supabase (vista)','inv_model_params','motor inv-engine (browser)','goldens Excel exactos: 46.70% / $186,668',null,'ok',3),
('Fix & Flip','Portal Inversionista','Métricas','Flujo mensual (portal)','Supabase (vista)','inv_ledger (RPC)','renta/gastos/deuda por mes','gastos con fecha futura EXCLUIDOS de la operación',null,'ok',4),
-- ═══ RENTAS · Property Manager ═══
('Rentas','Property Manager · Resumen','KPIs','% Ocupación','Supabase (vista)','v_ocupacion','ocupacion_pct','unidades ocupadas / rentables (48/45 = 93.75%)','antes había 2 denominadores distintos — unificado en v_ocupacion','ok',1),
('Rentas','Property Manager · Resumen','KPIs','Ingresos del mes','Rentas','💵 Pagos (espejo pm_payments)','Pago realizado + Mes/Año (billing_ym)','REGLA DURA: mes de dinero = MES DE RENTA (tag), jamás fecha de cobro',null,'ok',2),
('Rentas','Property Manager · Resumen','KPIs','Gastos del mes','Rentas','📤 Gastos X Casa (espejo pm_expenses)','Valor + billing_ym',null,null,'ok',3),
('Rentas','Property Manager · Resumen','KPIs','Cobrado en el mes (caja)','Rentas','💵 Pagos (espejo pm_payments)','paid_at','métrica SEPARADA de "mes de renta" — rotulada flujo de caja',null,'ok',4),
('Rentas','Propiedades','Ficha','Dirección','Rentas','🏠 Casas','Dirección','LLAVE con las otras bases (property_id canónico)',null,'ok',1),
('Rentas','Propiedades','Ficha','Unidades','Rentas','🚪 Unidades','count por casa (activas del Modelo Nuevo)','inactivas legacy NUNCA se muestran',null,'ok',2),
('Rentas','Propiedades','Ficha','Renta objetivo','Rentas','🚪 Unidades','Renta objetivo (target_rent)',null,null,'ok',3),
('Rentas','Propiedades','Ficha','WiFi / accesos','Rentas','🔑 Accesos (espejo pm_credentials)','código por unidad',null,null,'ok',4),
('Rentas','Inquilinos','Contratos','Monto Renta','Rentas','👤 Inquilinos','Monto Renta','⚠ 2 FUENTES: también FF·Propiedades·Renta mensual actual','definir canónica por pantalla en este mapa','warn',1),
('Rentas','Inquilinos','Contratos','Contrato inicio/fin','Rentas','👤 Inquilinos','Fecha Inicio / Fecha Fin',null,null,'ok',2),
('Rentas','Inquilinos','Contratos','Depósito','Rentas','👤 Inquilinos','Depósito','los depósitos NO son renta (regla del Cerebro)',null,'ok',3),
('Rentas','Pagos','Registro','Pago realizado','Rentas','💵 Pagos','Pago realizado (linked Casa/Inquilino/Reserva)','sin fuzzy matching — linked record IDs',null,'ok',1),
('Rentas','Pagos','Registro','Mes de renta','Rentas','💵 Pagos','Mes / Año (tag) → billing_ym',null,'7 gastos con Mes sin Año caen al año de la fecha','warn',2),
('Rentas','Pagos','Registro','Comprobante','Rentas','💵 Pagos','Comprobante','regla Silvia: pago sin soporte = check C14 del Sabueso',null,'ok',3),
('Rentas','Calendario / Reservas','Reservas','Reserva / unidad','Rentas','📅 Reservas','Reserva / Unidad / Fecha Entrada / Salida','cada habitación = fila individual (no colapsar)',null,'ok',1),
('Rentas','Gastos','Registro','Gasto por casa','Rentas','📤 Gastos X Casa','Valor / Tipo de Gasto / billing_ym',null,null,'ok',1),
('Rentas','Gastos','Registro','Gasto de empresa','Rentas','Gastos x Empresa (tbl9dJXwI9Vn3kjKy)','Valor / Ámbito','scope=empresa en el espejo','6 gastos de empresa sin Año (mayo) — taguear en Airtable','warn',2),
('Rentas','Gastos','Registro','Hipoteca (exclusión)','Rentas','📤 Gastos X Casa','descripción ~ hipoteca','EXCLUIDA del ledger inversionista (la cuota real viene de ff_hml_payments)','eran $257,751 duplicados — dedup clave','ok',3),
-- ═══ REMODELACIÓN ═══
('Remodelación','Command Center','Obra','Avance de obra','Remodelación','Propiedad en Reparación','Porcentaje avance obra % + avance_real (Planner)','v_remodel_progress (done/total) pisa el % manual',null,'ok',1),
('Remodelación','Command Center','Obra','Utilidad / margen','Remodelación','Propiedad en Reparación','Utilidad','ingreso (monto_real/draws) − costo_real (mat+MO ×1.05) — capa rcFin','desviación de costo usa presupuesto, no ingreso (+7% real, no +29%)','ok',2),
('Remodelación','Command Center','Obra','Retraso (días)','Remodelación','Propiedad en Reparación','Retraso en Dias','outliers |>180d| = "a revisar" (mediana)',null,'ok',3),
('Remodelación','Command Center','Obra','Draws ingresados','Remodelación','Propiedad en Reparación','Draws Ingresados',null,null,'ok',4),
('Remodelación','Estimador / Presupuesto','Costos','Presupuesto interno','Remodelación','Propiedad en Reparación','Presupuesto Remodelación interna',null,null,'ok',1),
('Remodelación','Estimador / Presupuesto','Costos','Gasto real (mat + MO)','Remodelación','Propiedad en Reparación','Gasto Materiales (Real) / Gasto trabajadores (Real)','+5% margen = gasto interno real (motor de cierre 9-jul)',null,'ok',2),
('Remodelación','Estimador / Presupuesto','Costos','$/sqft calibrado','Supabase (vista)','v_remodel_calib_costos','tendencia hist vs últimas 5','alimenta el Estimador (factor aplicado en rmAutoGenPlanner)',null,'ok',3),
('Remodelación','Planner','Avance','Avance real','Supabase (vista)','v_remodel_progress','tareas done/total por property_id','trigger trg_wa_progress recomputa on-write; write-back a Airtable (fld5nTFwW161Xu3sk)','⚠ AIRTABLE_TOKEN read-only en la base Remodel (write-back 403) — scope pendiente','warn',1),
('Remodelación','Planner','Avance','Baseline / desviación','Supabase (vista)','weekly_activities + remodel_stage_deviation','baseline_date vs fecha actual',null,null,'ok',2),
('Remodelación','Nómina de campo','Pagos','Horas / pago','Remodelación','Horas Trabajadas por Semana + Personal en Campo','horas × Pago x Hora','ledger v_remodel_nomina_ledger (grano trabajador×casa×día)','0 sin tarifa tras nómina POR LINK (13-jul)','ok',1),
('Remodelación','Reportes CEO','KPIs','EBITDA','Supabase (vista)','v_holding_pnl + remodel_overhead','ganancia bruta − overhead OPEX','capex vehículos excluido (CAPEX_RE)',null,'ok',1),
-- ═══ CONTABLE / QBO ═══
('Contable / QBO','Balance / Capital','Libros','Equity (en libros)','Contable / QBO','QuickBooks','Investor Contributions','espejo qb_report_cache (as_of visible)',null,'ok',1),
('Contable / QBO','Balance / Capital','Libros','Deuda HML','Contable / QBO','QuickBooks','Loan Payable – HML','vs HML vivo del OS (deals sin refi/venta) — C1 del Sabueso',null,'ok',2),
('Contable / QBO','Balance / Capital','Libros','Deuda refi','Contable / QBO','QuickBooks','HML-Refin','$1.22M sin espejo OS — falta campo "Monto Refi" en Airtable FF','dato con UNA fuente sola (QBO)','warn',3),
('Contable / QBO','Balance / Capital','Libros','Total Assets','Contable / QBO','QuickBooks','Balance Sheet','guard: equity contable ≤ assets (ci:gate)','labels case-insensitive ("TOTAL ASSETS")','ok',4),
('Contable / QBO','Balance / Capital','Capital','Capital desplegado','Supabase (vista)','v_capital_deployed','Airtable aportado + QBO','3 conceptos: comprometido (OS) / pagado (OS) / contabilizado (QBO) — diferencias de definición, no error',null,'ok',5),
('Contable / QBO','P&L / Resultados','Libros','Net Income YTD','Contable / QBO','QuickBooks','Profit & Loss',null,null,'ok',1),
('Contable / QBO','P&L / Resultados','Libros','Interés HML pagado','Contable / QBO','QuickBooks','Interest expense','vs ff_hml_payments (OS) — cruzan en v_pnl_casa',null,'ok',2),
('Contable / QBO','P&L / Resultados','Consolidado','P&L por casa','Supabase (vista)','v_pnl_casa','ingresos_renta − gastos_operativos − interes_hml_real','key property_id — alimenta ficha, portal inversionista y CC',null,'ok',3),
('Contable / QBO','Sabueso','Conciliación','$ sin conciliar','Supabase (vista)','ct_findings','Σ findings abiertos','norte: $0 = todo cuadra',null,'ok',1),
('Contable / QBO','Sabueso','Conciliación','Checks C1–C21','Supabase (vista)','ct_config + CierreEngine','umbrales en ct_config (cero hardcode)',null,null,'ok',2)
on conflict (empresa, sistema, dato) do nothing;
